services:
  mongo:
    image: mongo:7.0-jammy
    container_name: mongo
    ports: ["27017:27017"]
    volumes: [ "mongo_data:/data/db" ]
    healthcheck:
      test: ["CMD-SHELL", "mongosh --quiet --eval 'db.runCommand({ ping: 1 }).ok' | grep 1"]
      interval: 10s
      timeout: 5s
      retries: 10

  backend:
    build:
      context: .                # <-- ROOT repo supaya bisa COPY src/server dan src/shared
      dockerfile: src/server/Dockerfile
    container_name: backend
    ports: [ "8787:8787" ]
    environment:
      - WA_AUTH_DIR=/app/auth
      - NODE_ENV=production
      - PORT=8787
      - TZ=Asia/Jakarta
    volumes:
      - ./wa_auth:/app/auth
    restart: unless-stopped

  frontend:
    build:
      context: ./src/src
      dockerfile: Dockerfile
    container_name: frontend
    ports: [ "8080:80" ]
    depends_on: [ backend ]
    restart: unless-stopped
    environment:
      - VITE_API_URL=/api
    volumes:
      - ./src/src:/app
      - /app/node_modules

volumes:
  mongo_data:
